# config.yaml

wandb_project: "adCNN-src"
project_root: "."

device: "cuda"
num_workers: 4
pin_memory: true
model_dir: "./models"

model_type: "ResAD"  

# Models Configuration
models:
  CvT:
    model_params:
      # CvT-specific parameters
      type: "CvT"
      params:
        freeze_layers: true
        dropout_p: 0.5
        image_size: 256
        in_channels: 1
        num_classes: 1
        dim: 64
        kernels: [7, 3, 3]
        strides: [4, 2, 2]
        heads: [1, 3, 6]
        depth: [1, 2, 10]
        pool: "cls"
        emb_dropout: 0.1
        scale_dim: 4
    train_params:
      batch_size: 128
      num_epochs: 10
      early_stopping_patience: 5
      optimizer: "Adam"
      learning_rate: 0.001
      focal_gamma: 2.0
      scheduler_factor: 0.1
      scheduler_patience: 3

  ResAD:
    model_params:
      # ResAD-specific parameters
      type: "ResAD"
      params:
        num_classes: 1
        in_channels: 1
    train_params:
      batch_size: 64
      num_epochs: 15
      early_stopping_patience: 4
      optimizer: "SGD"
      learning_rate: 0.005
      focal_gamma: 1.5
      scheduler_factor: 0.05
      scheduler_patience: 2

# Dataset Configuration
datasets:
  type: "OASISKaggle"
  oasis_kaggle:
    class_name: "OASISKaggle"
    data_dir: "datasets/oasis_kaggle"
  adni:
    class_name: "ADNI"
    data_dir: "datasets/adni"

evaluate_params:
  focal_gamma: 2.0
  k_hard_examples: 32

transform:
  resize: [256, 256]
  skull_strip: true
  grayscale: 1
  horizontal_flip: 0.5
  rotation: 15
  color_jitter:
    brightness: 0.2
    contrast: 0.2
    saturation: 0.2
    hue: 0.1
  normalize:
    mean: [0.485]
    std: [0.229]

