name: adCNN
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.9
  - pytorch=2.4
  - torchvision=0.19
  - torchmetrics
  - cudatoolkit
  - tqdm
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - pillow
  - rich
  - pip
  - pip:
      - nibabel
      - kaggle
      - wandb
