name: adCNN
channels:
 - pytorch
 - nvidia
 - defaults
dependencies:
  - python
  - pytorch
  - torchvision
  - torchmetrics
  - pytorch-cuda=12.4
  - tqdm
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - pillow
  - rich
  - pip
  - pip:
      - nibabel
      - kaggle
      - wandb
      - tamllint
