name: adCNN
channels:
  - defaults
  - pytorch
dependencies:
  - python
  - cudatoolkit
  - tqdm
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - pillow
  - pytorch
  - torchvision
  - torchmetrics
  - tensorboard
  - rich
  - pip
  - pip:
      - nibabel
      - kaggle
