program: src/main.py
method: bayes
metric:
  name: Validation F1-Score
  goal: maximize
parameters:
  learning_rate:
    distribution: uniform
    min: 0.0001
    max: 0.01
  batch_size:
    values: [32, 64, 128]
  optimizer:
    values: ["Adam", "SGD"]
  focal_gamma:
    values: [1.0, 2.0, 3.0]
  dropout:
    distribution: uniform
    min: 0.3
    max: 0.7
  model_type:
    values: ["ResAD", ]
  dataset_type:
    values: ["OASISKaggle", ]  
command:
  - python
  - src/main.py
  - --step
  - train
