_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.8.19
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 1
                - 2
                - 3
                - 13
                - 15
                - 16
                - 23
                - 55
                - 62
            "4": 3.8.19
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size:
    value: 32
experiment_dir:
    value: models
focal_gamma:
    value: 2
git_commit:
    value: aabb7218ae13fad93de99ad90bf7a444ad6b9e60
learning_rate:
    value: 0.0001
log_dir:
    value: models
loss_function:
    value: FocalLoss
model:
    value: ResAD
num_epochs:
    value: 20
optimizer:
    value: Adam
scheduler_factor:
    value: 0.1
scheduler_patience:
    value: 2
